version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: zpi-db
      POSTGRES_USER: zpi-user
      POSTGRES_PASSWORD: test41test?
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  
  # zpi-backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
