FROM openjdk:17

# Application must be packaged after changes before building container
ARG JAR_FILE=*.jar

WORKDIR /ZPI-BACKEND

COPY target/${JAR_FILE} application.jar

EXPOSE 8080

CMD ["java", "-jar", "application.jar"]
