version: '3'

services:
  app:
      image: 'docker-spring-boot-postgres:latest'
      build:
        context: .
      container_name: app
      depends_on:
        - db
      ports:
      - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zpi-db
        SPRING_DATASOURCE_USERNAME: test
        SPRING_DATASOURCE_PASSWORD: test
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zpi-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "1234:80"
    depends_on:
      - db

