# FROM openjdk:11-jre-slim

# WORKDIR /backend

# # Copy the application JAR file into the container at /app
# COPY target/zpi-backend.jar /backend/zpi-backend.jar

# # Expose the port that the application will run on
# EXPOSE 8080

# # Specify the command to run on container startup
# CMD ["java", "-jar", "zpi-backend.jar"]
